version: '3'
services:
  frontend:
    build:
      context: ./client
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - '5000:5000'
    environment:
      - JWT_SECRET=your_jwt_secret
